name: Set up Apache Qpid Broker J

on: [push]

env:
  QPID_VERSION: "7.1.0"

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Download Apache Qpid Broker J
      run: |
        wget https://downloads.apache.org/qpid/java/7.1.0/binaries/qpid-broker-j-${QPID_VERSION}-bin.tar.gz
        tar -xf qpid-broker-j-${QPID_VERSION}-bin.tar.gz

    - name: Start Apache Qpid Broker J
      run: |
        cd qpid-broker-j-${QPID_VERSION}/bin
        ./qpid-server start
